version: "3"
services:
  frontend:
    image: frontend-angular
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend-app"
    ports:
      - "4200:4200"
  backend:
    image: backend-flask
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "backend-app"
    ports:
      - "8081:8081" # if changed, please change port in `frontend/proxy.conf.dev.json`
